/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ILGuardManager {
  export type PositionStruct = {
    owner: AddressLike;
    tokenId: BigNumberish;
    tickLower: BigNumberish;
    tickUpper: BigNumberish;
    liquidity: BigNumberish;
    isProtected: boolean;
    isPaused: boolean;
    createdAt: BigNumberish;
    lastRebalanceAt: BigNumberish;
  };

  export type PositionStructOutput = [
    owner: string,
    tokenId: bigint,
    tickLower: bigint,
    tickUpper: bigint,
    liquidity: bigint,
    isProtected: boolean,
    isPaused: boolean,
    createdAt: bigint,
    lastRebalanceAt: bigint
  ] & {
    owner: string;
    tokenId: bigint;
    tickLower: bigint;
    tickUpper: bigint;
    liquidity: bigint;
    isProtected: boolean;
    isPaused: boolean;
    createdAt: bigint;
    lastRebalanceAt: bigint;
  };
}

export interface ILGuardManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "botAddress"
      | "canRebalance"
      | "cooldownPeriod"
      | "dailyActionCounts"
      | "deposit"
      | "emergencyPause"
      | "emergencyPausePosition"
      | "getPosition"
      | "getUserPositions"
      | "maxActionsPerDay"
      | "owner"
      | "paused"
      | "positions"
      | "rebalance"
      | "renounceOwnership"
      | "setBotAddress"
      | "setCooldownPeriod"
      | "setMaxActionsPerDay"
      | "setSlippageTolerance"
      | "slippageTolerance"
      | "toggleProtection"
      | "transferOwnership"
      | "unpause"
      | "unpausePosition"
      | "userPositions"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BotAddressUpdated"
      | "Deposited"
      | "OwnershipTransferred"
      | "Paused"
      | "PositionPaused"
      | "PositionUnpaused"
      | "ProtectionToggled"
      | "Rebalanced"
      | "SlippageToleranceUpdated"
      | "Unpaused"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "botAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canRebalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyActionCounts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPausePosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxActionsPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBotAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxActionsPerDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageTolerance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slippageTolerance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleProtection",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unpausePosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "botAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyActionCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPausePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxActionsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBotAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxActionsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpausePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BotAddressUpdatedEvent {
  export type InputTuple = [oldBot: AddressLike, newBot: AddressLike];
  export type OutputTuple = [oldBot: string, newBot: string];
  export interface OutputObject {
    oldBot: string;
    newBot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    amount0: bigint,
    amount1: bigint,
    tickLower: bigint,
    tickUpper: bigint,
    liquidity: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    amount0: bigint;
    amount1: bigint;
    tickLower: bigint;
    tickUpper: bigint;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionPausedEvent {
  export type InputTuple = [positionId: BigNumberish, user: AddressLike];
  export type OutputTuple = [positionId: bigint, user: string];
  export interface OutputObject {
    positionId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionUnpausedEvent {
  export type InputTuple = [positionId: BigNumberish, user: AddressLike];
  export type OutputTuple = [positionId: bigint, user: string];
  export interface OutputObject {
    positionId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtectionToggledEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    isProtected: boolean
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    isProtected: boolean
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    isProtected: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    oldTickLower: BigNumberish,
    oldTickUpper: BigNumberish,
    newTickLower: BigNumberish,
    newTickUpper: BigNumberish,
    reason: string,
    feesCollected: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    oldTickLower: bigint,
    oldTickUpper: bigint,
    newTickLower: bigint,
    newTickUpper: bigint,
    reason: string,
    feesCollected: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    oldTickLower: bigint;
    oldTickUpper: bigint;
    newTickLower: bigint;
    newTickUpper: bigint;
    reason: string;
    feesCollected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlippageToleranceUpdatedEvent {
  export type InputTuple = [
    oldTolerance: BigNumberish,
    newTolerance: BigNumberish
  ];
  export type OutputTuple = [oldTolerance: bigint, newTolerance: bigint];
  export interface OutputObject {
    oldTolerance: bigint;
    newTolerance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    feesCollected: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    amount0: bigint,
    amount1: bigint,
    feesCollected: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    amount0: bigint;
    amount1: bigint;
    feesCollected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILGuardManager extends BaseContract {
  connect(runner?: ContractRunner | null): ILGuardManager;
  waitForDeployment(): Promise<this>;

  interface: ILGuardManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  botAddress: TypedContractMethod<[], [string], "view">;

  canRebalance: TypedContractMethod<
    [positionId: BigNumberish],
    [boolean],
    "view"
  >;

  cooldownPeriod: TypedContractMethod<[], [bigint], "view">;

  dailyActionCounts: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<
    [
      amount0: BigNumberish,
      amount1: BigNumberish,
      tickLower: BigNumberish,
      tickUpper: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyPausePosition: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [ILGuardManager.PositionStructOutput],
    "view"
  >;

  getUserPositions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  maxActionsPerDay: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        tokenId: bigint;
        tickLower: bigint;
        tickUpper: bigint;
        liquidity: bigint;
        isProtected: boolean;
        isPaused: boolean;
        createdAt: bigint;
        lastRebalanceAt: bigint;
      }
    ],
    "view"
  >;

  rebalance: TypedContractMethod<
    [
      positionId: BigNumberish,
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBotAddress: TypedContractMethod<
    [newBotAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setCooldownPeriod: TypedContractMethod<
    [newCooldownPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxActionsPerDay: TypedContractMethod<
    [newMaxActions: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSlippageTolerance: TypedContractMethod<
    [newTolerance: BigNumberish],
    [void],
    "nonpayable"
  >;

  slippageTolerance: TypedContractMethod<[], [bigint], "view">;

  toggleProtection: TypedContractMethod<
    [positionId: BigNumberish, isProtected: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unpausePosition: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "botAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canRebalance"
  ): TypedContractMethod<[positionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cooldownPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyActionCounts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      amount0: BigNumberish,
      amount1: BigNumberish,
      tickLower: BigNumberish,
      tickUpper: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyPausePosition"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [ILGuardManager.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "maxActionsPerDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        tokenId: bigint;
        tickLower: bigint;
        tickUpper: bigint;
        liquidity: bigint;
        isProtected: boolean;
        isPaused: boolean;
        createdAt: bigint;
        lastRebalanceAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBotAddress"
  ): TypedContractMethod<[newBotAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCooldownPeriod"
  ): TypedContractMethod<
    [newCooldownPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxActionsPerDay"
  ): TypedContractMethod<[newMaxActions: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlippageTolerance"
  ): TypedContractMethod<[newTolerance: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slippageTolerance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "toggleProtection"
  ): TypedContractMethod<
    [positionId: BigNumberish, isProtected: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpausePosition"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BotAddressUpdated"
  ): TypedContractEvent<
    BotAddressUpdatedEvent.InputTuple,
    BotAddressUpdatedEvent.OutputTuple,
    BotAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PositionPaused"
  ): TypedContractEvent<
    PositionPausedEvent.InputTuple,
    PositionPausedEvent.OutputTuple,
    PositionPausedEvent.OutputObject
  >;
  getEvent(
    key: "PositionUnpaused"
  ): TypedContractEvent<
    PositionUnpausedEvent.InputTuple,
    PositionUnpausedEvent.OutputTuple,
    PositionUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtectionToggled"
  ): TypedContractEvent<
    ProtectionToggledEvent.InputTuple,
    ProtectionToggledEvent.OutputTuple,
    ProtectionToggledEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;
  getEvent(
    key: "SlippageToleranceUpdated"
  ): TypedContractEvent<
    SlippageToleranceUpdatedEvent.InputTuple,
    SlippageToleranceUpdatedEvent.OutputTuple,
    SlippageToleranceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "BotAddressUpdated(address,address)": TypedContractEvent<
      BotAddressUpdatedEvent.InputTuple,
      BotAddressUpdatedEvent.OutputTuple,
      BotAddressUpdatedEvent.OutputObject
    >;
    BotAddressUpdated: TypedContractEvent<
      BotAddressUpdatedEvent.InputTuple,
      BotAddressUpdatedEvent.OutputTuple,
      BotAddressUpdatedEvent.OutputObject
    >;

    "Deposited(uint256,address,uint256,uint256,int24,int24,uint128)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PositionPaused(uint256,address)": TypedContractEvent<
      PositionPausedEvent.InputTuple,
      PositionPausedEvent.OutputTuple,
      PositionPausedEvent.OutputObject
    >;
    PositionPaused: TypedContractEvent<
      PositionPausedEvent.InputTuple,
      PositionPausedEvent.OutputTuple,
      PositionPausedEvent.OutputObject
    >;

    "PositionUnpaused(uint256,address)": TypedContractEvent<
      PositionUnpausedEvent.InputTuple,
      PositionUnpausedEvent.OutputTuple,
      PositionUnpausedEvent.OutputObject
    >;
    PositionUnpaused: TypedContractEvent<
      PositionUnpausedEvent.InputTuple,
      PositionUnpausedEvent.OutputTuple,
      PositionUnpausedEvent.OutputObject
    >;

    "ProtectionToggled(uint256,address,bool)": TypedContractEvent<
      ProtectionToggledEvent.InputTuple,
      ProtectionToggledEvent.OutputTuple,
      ProtectionToggledEvent.OutputObject
    >;
    ProtectionToggled: TypedContractEvent<
      ProtectionToggledEvent.InputTuple,
      ProtectionToggledEvent.OutputTuple,
      ProtectionToggledEvent.OutputObject
    >;

    "Rebalanced(uint256,address,int24,int24,int24,int24,string,uint256)": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;

    "SlippageToleranceUpdated(uint256,uint256)": TypedContractEvent<
      SlippageToleranceUpdatedEvent.InputTuple,
      SlippageToleranceUpdatedEvent.OutputTuple,
      SlippageToleranceUpdatedEvent.OutputObject
    >;
    SlippageToleranceUpdated: TypedContractEvent<
      SlippageToleranceUpdatedEvent.InputTuple,
      SlippageToleranceUpdatedEvent.OutputTuple,
      SlippageToleranceUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
