/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { ILGuardManager__factory } from "./ILGuardManager__factory";
